import { chromium } from 'playwright-core';
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});
const page=await browser.newPage({viewport:{width:390,height:844}});
await page.goto(process.env.BASE_URL??'http://127.0.0.1:3100');
await page.locator('h1').filter({hasText:'ダッシュボード'}).waitFor();
await page.screenshot({path:'tmp/dashboard-smoke.png',fullPage:true});
const text=await page.locator('#dashboard').innerText();
if(!text.includes('水煮加工')||!text.includes('チップス加工'))throw new Error('工程フローが表示されていません');
await page.getByRole('button',{name:'青果'}).click();
await page.getByText('検品実測数量').first().waitFor();
const viewportWidth=await page.evaluate(()=>document.documentElement.clientWidth);
const contentWidth=await page.evaluate(()=>document.documentElement.scrollWidth);
if(contentWidth>viewportWidth)throw new Error(`横スクロールが発生しています: ${contentWidth}/${viewportWidth}`);
await page.getByRole('button',{name:'メニューを開く'}).click();
await page.getByRole('button',{name:'工程実績入力'}).click();
await page.locator('#processForm').waitFor();
if(await page.locator('#dashboardView').isVisible())throw new Error('入力画面とダッシュボードが同時に表示されています');
await page.getByRole('button',{name:'メニューを開く'}).click();
await page.getByRole('button',{name:'その他の入力'}).click();
await page.getByRole('button',{name:'検品入力'}).click();
await page.locator('#receiptForm').waitFor();
if((await page.evaluate(()=>document.documentElement.scrollWidth))>(await page.evaluate(()=>document.documentElement.clientWidth)))throw new Error('入力画面で横スクロールが発生しています');
await page.getByRole('button',{name:'マスタ管理'}).click();
await page.getByRole('heading',{name:'従業員マスタ'}).waitFor();
for(const label of ['時給（労務費計算用）','LINE連携対象','在籍状態'])if(!(await page.locator('#employeeMasterForm').innerText()).includes(label))throw new Error(`従業員マスタ項目がありません: ${label}`);
await browser.close();
