import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { db, audit, now, transaction } from './db.js';
import { workMinutes } from './domain.js';

const rows=(sql,...args)=>db.prepare(sql).all(...args),one=(sql,...args)=>db.prepare(sql).get(...args);
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify({data}));};
const fail=(res,error,status=400)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify({error:{message:error.message??String(error)}}));};
const required=(value,label)=>{if(value===undefined||value===null||value==='')throw new Error(`${label}は必須です`);return value;};
const hash=value=>createHash('sha256').update(String(value)).digest('hex');
const adminTokens=new Map();
const cookieMap=req=>Object.fromEntries((req.headers.cookie??'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))];}));
const bodyText=async req=>{const chunks=[];for await(const chunk of req)chunks.push(chunk);return Buffer.concat(chunks).toString('utf8');};
const bodyJson=async req=>{const text=await bodyText(req);return {text,value:text?JSON.parse(text):{}};};
const defaultCompany=()=>one("SELECT * FROM companies WHERE code='triangle' AND active=1");
const settings=companyId=>one('SELECT * FROM company_settings WHERE company_id=?',companyId);
const safeEqual=(a,b)=>{const aa=Buffer.from(String(a)),bb=Buffer.from(String(b));return aa.length===bb.length&&timingSafeEqual(aa,bb);};

function requireAdmin(req,res){const token=cookieMap(req).wf_admin,expires=adminTokens.get(token);if(!token||!expires||expires<Date.now()){if(token)adminTokens.delete(token);fail(res,new Error('管理者PINの確認が必要です'),401);return false;}return true;}
function verifyN8n(req,text){const secret=process.env.N8N_SHARED_SECRET;if(!secret)throw Object.assign(new Error('N8N_SHARED_SECRETが未設定です'),{status:503});const eventId=required(req.headers['x-wf-event-id'],'イベントID'),timestamp=required(req.headers['x-wf-timestamp'],'送信時刻'),signature=required(req.headers['x-wf-signature'],'署名');const sent=Date.parse(timestamp);if(!Number.isFinite(sent)||Math.abs(Date.now()-sent)>Number(process.env.N8N_SIGNATURE_TOLERANCE_SECONDS??300)*1000)throw Object.assign(new Error('送信時刻が許容範囲外です'),{status:401});const expected=createHmac('sha256',secret).update(`${eventId}.${timestamp}.${text}`).digest('hex');if(!safeEqual(signature,expected))throw Object.assign(new Error('署名が不正です'),{status:401});return {eventId,timestamp};}
function activeSession(employeeId){return one("SELECT w.*,p.name process_name,product.name product_name FROM work_sessions w JOIN processes p ON p.id=w.process_id LEFT JOIN products product ON product.id=w.product_id WHERE w.employee_id=? AND w.status IN ('running','working','break') ORDER BY w.id DESC LIMIT 1",employeeId);}
function lineUser(companyId,lineUserId){return one('SELECT lu.*,e.name employee_name FROM line_users lu JOIN employees e ON e.id=lu.employee_id WHERE lu.company_id=? AND lu.line_user_id=? AND lu.active=1',companyId,lineUserId);}
function menu(companyId,parentId=null){return rows(`SELECT m.id,m.code,m.label,m.parent_id,m.department_id,m.process_id,m.product_id FROM line_menu_items m WHERE m.company_id=? AND m.active=1 AND ${parentId==null?'m.parent_id IS NULL':'m.parent_id=?'} ORDER BY m.sort_order,m.id`,...(parentId==null?[companyId]:[companyId,parentId]));}
function statePayload(companyId,user){const session=activeSession(user.employee_id);if(!session)return {state:'idle',message:'作業を選択してください',menu:menu(companyId)};if(session.status==='break')return {state:'break',message:'休憩中',session,buttons:['resume','end']};return {state:'working',message:`現在：${session.product_name??session.process_name}作業中`,session,buttons:['end','break_start']};}
function fixedBreakMinutes(companyId,startedAt,endedAt){const defs=rows('SELECT * FROM company_fixed_breaks WHERE company_id=? AND active=1 ORDER BY sort_order',companyId);if(!defs.length)return 0;const start=new Date(startedAt),end=new Date(endedAt),jst=9*60*60000,localStart=new Date(start.getTime()+jst),localEnd=new Date(end.getTime()+jst);let total=0;for(let cursor=new Date(Date.UTC(localStart.getUTCFullYear(),localStart.getUTCMonth(),localStart.getUTCDate()));cursor<=localEnd;cursor.setUTCDate(cursor.getUTCDate()+1)){const day=cursor.toISOString().slice(0,10);for(const def of defs){let bStart=new Date(`${day}T${def.start_time}:00+09:00`),bEnd=new Date(`${day}T${def.end_time}:00+09:00`);if(bEnd<=bStart)bEnd=new Date(bEnd.getTime()+86400000);const overlap=Math.max(0,Math.min(end,bEnd)-Math.max(start,bStart));total+=overlap/60000;}}return Math.round(total);}
function closeOpenBreak(sessionId,endedAt){const open=one('SELECT * FROM work_breaks WHERE work_session_id=? AND ended_at IS NULL ORDER BY id DESC LIMIT 1',sessionId);if(open){const minutes=Math.max(0,workMinutes(open.started_at,endedAt,0));db.prepare('UPDATE work_breaks SET ended_at=?,minutes=?,updated_at=? WHERE id=?').run(endedAt,minutes,now(),open.id);}}
function completeSession(session,endedAt,companySettings){closeOpenBreak(session.id,endedAt);let breaks=0;if(companySettings.break_mode==='line')breaks=Number(one('SELECT COALESCE(SUM(minutes),0) total FROM work_breaks WHERE work_session_id=?',session.id).total);else if(companySettings.break_mode==='fixed')breaks=fixedBreakMinutes(session.company_id,session.started_at,endedAt);else if(companySettings.break_mode==='admin')breaks=Number(session.break_minutes??0);const minutes=workMinutes(session.started_at,endedAt,breaks);db.prepare("UPDATE work_sessions SET ended_at=?,break_minutes=?,minutes=?,status='completed',updated_at=? WHERE id=?").run(endedAt,breaks,minutes,now(),session.id);return {minutes,break_minutes:breaks};}
function queueNotification(companyId,sessionId,type,recipientType,recipientKey,payload){db.prepare('INSERT INTO notification_logs(company_id,work_session_id,notification_type,recipient_type,recipient_key,payload_json,created_at) VALUES(?,?,?,?,?,?,?)').run(companyId,sessionId,type,recipientType,recipientKey??null,JSON.stringify(payload),now());}

function processLineEvent(company,eventId,input){
  const companySettings=settings(company.id);
  if(!companySettings?.line_enabled)throw new Error('LINE連携は停止中です');
  const requestedAction=required(input.action,'操作');
  const action=requestedAction==='finish'?'end':requestedAction;
  const lineId=required(input.line_user_id,'LINE UserID');
  if(action==='register'){
    const registration=one('SELECT * FROM line_registration_codes WHERE company_id=? AND code_hash=? AND used_at IS NULL AND expires_at>?',company.id,hash(required(input.registration_code,'登録コード')),now());
    if(!registration)throw new Error('登録コードが無効または期限切れです');
    transaction(()=>{
      db.prepare(`INSERT INTO line_users(company_id,employee_id,line_user_id,display_name,linked_at) VALUES(?,?,?,?,?)
        ON CONFLICT(company_id,employee_id) DO UPDATE SET line_user_id=excluded.line_user_id,display_name=excluded.display_name,active=1,linked_at=excluded.linked_at,unlinked_at=NULL`).run(company.id,registration.employee_id,lineId,input.display_name??null,now());
      db.prepare('UPDATE line_registration_codes SET used_at=? WHERE id=?').run(now(),registration.id);
    });
    const registered=lineUser(company.id,lineId);
    return {...statePayload(company.id,registered),message:`${registered.employee_name}さんの登録が完了しました`};
  }
  const user=lineUser(company.id,lineId);
  if(!user)throw new Error('従業員登録が必要です');
  if(action==='status'||action==='menu')return statePayload(company.id,user);
  const current=activeSession(user.employee_id);
  if(action==='start'){
    if(current)throw new Error(current.status==='break'?'休憩中は他工程を開始できません':'進行中の作業を先に終了してください');
    const item=one('SELECT * FROM line_menu_items WHERE company_id=? AND (id=? OR code=?) AND active=1',company.id,input.menu_item_id??-1,input.menu_code??'');
    if(!item)throw new Error('作業メニューがありません');
    const children=menu(company.id,item.id);
    if(children.length)return {state:'submenu',message:`${item.label}の内容を選択してください`,menu:children};
    if(!item.process_id)throw new Error('工程が設定されていません');
    const occurred=input.occurred_at??now();
    const result=db.prepare(`INSERT INTO work_sessions(company_id,employee_id,department_id,process_id,product_id,work_date,started_at,source_type,status,external_id,break_mode,created_at,updated_at)
      VALUES(?,?,?,?,?,?,?,'line','working',?,?,?,?)`).run(company.id,user.employee_id,item.department_id,item.process_id,item.product_id??null,occurred.slice(0,10),occurred,eventId,companySettings.break_mode,now(),now());
    queueNotification(company.id,Number(result.lastInsertRowid),'work_started','employee',lineId,{message:`${item.label}を開始しました`});
    return statePayload(company.id,user);
  }
  if(!current)throw new Error('進行中の作業がありません');
  if(action==='break_start'){
    if(current.status==='break')throw new Error('すでに休憩中です');
    if(companySettings.break_mode!=='line')throw new Error('会社設定がLINE休憩打刻ではありません');
    db.prepare("INSERT INTO work_breaks(work_session_id,started_at,source_type,created_at,updated_at) VALUES(?,?,'line',?,?)").run(current.id,input.occurred_at??now(),now(),now());
    db.prepare("UPDATE work_sessions SET status='break',updated_at=? WHERE id=?").run(now(),current.id);
    return statePayload(company.id,user);
  }
  if(action==='resume'){
    if(current.status!=='break')throw new Error('休憩中ではありません');
    closeOpenBreak(current.id,input.occurred_at??now());
    db.prepare("UPDATE work_sessions SET status='working',updated_at=? WHERE id=?").run(now(),current.id);
    return statePayload(company.id,user);
  }
  if(action==='end'){
    const result=completeSession(current,input.occurred_at??now(),companySettings);
    queueNotification(company.id,current.id,'work_ended','employee',lineId,{message:`作業を終了しました（${result.minutes}分）`});
    return {state:'idle',message:`作業を終了しました（作業${result.minutes}分・休憩${result.break_minutes}分）`,menu:menu(company.id)};
  }
  throw new Error('操作が不正です');
}

async function n8nEvent(req,res,company){const text=await bodyText(req),headerEventId=req.headers['x-wf-event-id']??null,lineEventId=Number(db.prepare("INSERT INTO line_events(company_id,event_id,received_at,raw_json,status) VALUES(?,?,?,?,'received')").run(company.id,headerEventId,now(),text).lastInsertRowid);let value,verified;try{value=text?JSON.parse(text):{};verified=verifyN8n(req,text);if(value.event_id!==undefined&&value.event_id!==verified.eventId)throw Object.assign(new Error('本文とヘッダーのEventIDが一致しません'),{status:400});}catch(error){db.prepare("UPDATE line_events SET status='error',processed_at=?,error_message=? WHERE id=?").run(now(),error.message,lineEventId);return fail(res,error,error.status??400);}const existing=one("SELECT response_json,status FROM external_events WHERE company_id=? AND source='n8n_line' AND event_id=?",company.id,verified.eventId);if(existing){db.prepare("UPDATE line_events SET status='duplicate',processed_at=? WHERE id=?").run(now(),lineEventId);return json(res,200,{...JSON.parse(existing.response_json??'{}'),duplicate:true});}const eventRow=Number(db.prepare("INSERT INTO external_events(company_id,source,event_id,occurred_at,received_at,payload_json,status) VALUES(?,'n8n_line',?,?,?,?, 'received')").run(company.id,verified.eventId,value.occurred_at??verified.timestamp,now(),text).lastInsertRowid);try{const result=processLineEvent(company,verified.eventId,value);transaction(()=>{db.prepare("UPDATE external_events SET status='processed',response_json=?,processed_at=? WHERE id=?").run(JSON.stringify(result),now(),eventRow);db.prepare("UPDATE line_events SET status='processed',processed_at=? WHERE id=?").run(now(),lineEventId);});return json(res,200,result);}catch(error){const result={state:'error',message:error.message,notify:['employee','manager']};transaction(()=>{db.prepare("UPDATE external_events SET status='error',response_json=?,error_message=?,processed_at=? WHERE id=?").run(JSON.stringify(result),error.message,now(),eventRow);db.prepare("UPDATE line_events SET status='error',processed_at=?,error_message=? WHERE id=?").run(now(),error.message,lineEventId);});return json(res,400,result);}}

export async function handlePhase2A(req,res,url,user){const company=defaultCompany();if(!company)return false;
  if(req.method==='POST'&&url.pathname==='/api/v1/admin/unlock'){const {value}=await bodyJson(req),pin=process.env.ADMIN_PIN;if(!pin)return fail(res,new Error('ADMIN_PINが未設定です'),503),true;if(!safeEqual(value.pin??'',pin))return fail(res,new Error('PINが違います'),401),true;const token=randomBytes(24).toString('hex');adminTokens.set(token,Date.now()+Number(process.env.ADMIN_SESSION_MINUTES??30)*60000);res.writeHead(200,{'content-type':'application/json; charset=utf-8','set-cookie':`wf_admin=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Number(process.env.ADMIN_SESSION_MINUTES??30)*60}`});res.end(JSON.stringify({data:{ok:true}}));return true;}
  if(req.method==='POST'&&url.pathname==='/api/v1/integrations/n8n/line-events'){await n8nEvent(req,res,company);return true;}
  if(req.method==='POST'&&url.pathname==='/api/v1/integrations/n8n/unfinished-check'){const {text,value}=await bodyJson(req);try{verifyN8n(req,text);}catch(error){fail(res,error,error.status??401);return true;}const s=settings(company.id),at=new Date(value.now??now()),open=rows("SELECT w.*,e.name employee_name,lu.line_user_id,p.name process_name FROM work_sessions w JOIN employees e ON e.id=w.employee_id JOIN processes p ON p.id=w.process_id LEFT JOIN line_users lu ON lu.employee_id=w.employee_id AND lu.company_id=w.company_id AND lu.active=1 WHERE w.company_id=? AND w.status IN ('running','working','break')",company.id).filter(w=>{const threshold=new Date(`${w.work_date}T${s.standard_end_time}:00+09:00`).getTime()+s.grace_minutes*60000;return at.getTime()>threshold;});if(s.unfinished_notification_enabled){for(const w of open){const already=one("SELECT id FROM notification_logs WHERE work_session_id=? AND notification_type='unfinished' AND created_at>=? LIMIT 1",w.id,w.work_date);if(already)continue;queueNotification(company.id,w.id,'unfinished','employee',w.line_user_id,{employee:w.employee_name,process:w.process_name});queueNotification(company.id,w.id,'unfinished','manager',null,{employee:w.employee_name,process:w.process_name});}}json(res,200,{sessions:open,notify:s.unfinished_notification_enabled?['employee','manager']:[]});return true;}
  if(!url.pathname.startsWith('/api/v1/admin/'))return false;if(!requireAdmin(req,res))return true;
  if(req.method==='GET'&&url.pathname==='/api/v1/admin/line-users'){json(res,200,{users:rows('SELECT e.id employee_id,e.name,lu.line_user_id,lu.display_name,lu.is_manager,lu.active linked FROM employees e LEFT JOIN line_users lu ON lu.employee_id=e.id AND lu.company_id=? ORDER BY e.name',company.id)});return true;}
  if(req.method==='POST'&&url.pathname==='/api/v1/admin/line-registration-codes'){const {value}=await bodyJson(req),code=randomBytes(4).toString('hex').toUpperCase(),expires=new Date(Date.now()+Number(value.valid_minutes??60)*60000).toISOString();db.prepare('INSERT INTO line_registration_codes(company_id,employee_id,code_hash,expires_at,created_at) VALUES(?,?,?,?,?)').run(company.id,required(value.employee_id,'従業員'),hash(code),expires,now());audit(user,'CREATE','line_registration_code',value.employee_id);json(res,201,{code,expires_at:expires});return true;}
  const unlink=url.pathname.match(/^\/api\/v1\/admin\/line-users\/(\d+)\/unlink$/);if(req.method==='POST'&&unlink){db.prepare('UPDATE line_users SET active=0,unlinked_at=? WHERE company_id=? AND employee_id=?').run(now(),company.id,Number(unlink[1]));audit(user,'UNLINK','line_user',unlink[1]);json(res,200,{ok:true});return true;}
  if(req.method==='GET'&&url.pathname==='/api/v1/admin/work-sessions'){const q=url.searchParams;json(res,200,{sessions:rows(`SELECT w.*,e.name employee_name,p.name process_name,d.name department_name,(SELECT COUNT(*) FROM work_breaks b WHERE b.work_session_id=w.id) break_count FROM work_sessions w JOIN employees e ON e.id=w.employee_id JOIN processes p ON p.id=w.process_id JOIN departments d ON d.id=w.department_id WHERE w.company_id=? AND (? IS NULL OR w.work_date=?) AND (? IS NULL OR w.employee_id=?) AND (? IS NULL OR w.department_id=?) AND (? IS NULL OR w.process_id=?) ORDER BY w.started_at DESC`,company.id,q.get('date'),q.get('date'),q.get('employee_id'),q.get('employee_id'),q.get('department_id'),q.get('department_id'),q.get('process_id'),q.get('process_id'))});return true;}
  const correction=url.pathname.match(/^\/api\/v1\/admin\/work-sessions\/(\d+)$/);if(req.method==='PATCH'&&correction){const {value}=await bodyJson(req),id=Number(correction[1]),before=one('SELECT * FROM work_sessions WHERE id=? AND company_id=?',id,company.id);if(!before)return fail(res,new Error('作業履歴がありません'),404),true;const after={...before,started_at:value.started_at??before.started_at,ended_at:value.ended_at??before.ended_at,process_id:Number(value.process_id??before.process_id),break_minutes:Number(value.break_minutes??before.break_minutes)};after.minutes=after.ended_at?workMinutes(after.started_at,after.ended_at,after.break_minutes):null;transaction(()=>{db.prepare('UPDATE work_sessions SET started_at=?,ended_at=?,process_id=?,break_minutes=?,minutes=?,status=?,exception_reason=?,updated_at=? WHERE id=?').run(after.started_at,after.ended_at,after.process_id,after.break_minutes,after.minutes,after.ended_at?'completed':before.status,required(value.reason,'修正理由'),now(),id);db.prepare('INSERT INTO work_session_corrections(work_session_id,reason,before_json,after_json,corrected_at) VALUES(?,?,?,?,?)').run(id,value.reason,JSON.stringify(before),JSON.stringify(after),now());audit(user,'CORRECT','work_session',id,{reason:value.reason});});json(res,200,{ok:true,minutes:after.minutes});return true;}
  if(req.method==='GET'&&url.pathname==='/api/v1/admin/company-settings'){json(res,200,{company,settings:settings(company.id),fixed_breaks:rows('SELECT * FROM company_fixed_breaks WHERE company_id=? AND active=1 ORDER BY sort_order,id',company.id),menu_items:rows('SELECT * FROM line_menu_items WHERE company_id=? ORDER BY parent_id,sort_order,id',company.id)});return true;}
  if(req.method==='PATCH'&&url.pathname==='/api/v1/admin/company-settings'){const {value}=await bodyJson(req),cur=settings(company.id);db.prepare('UPDATE company_settings SET standard_end_time=?,grace_minutes=?,break_mode=?,line_enabled=?,unfinished_notification_enabled=?,updated_at=? WHERE company_id=?').run(value.standard_end_time??cur.standard_end_time,Number(value.grace_minutes??cur.grace_minutes),value.break_mode??cur.break_mode,value.line_enabled===undefined?cur.line_enabled:value.line_enabled?1:0,value.unfinished_notification_enabled===undefined?cur.unfinished_notification_enabled:value.unfinished_notification_enabled?1:0,now(),company.id);audit(user,'UPDATE','company_settings',company.id,value);json(res,200,{ok:true});return true;}
  if(req.method==='POST'&&url.pathname==='/api/v1/admin/fixed-breaks'){const {value}=await bodyJson(req);const id=Number(db.prepare('INSERT INTO company_fixed_breaks(company_id,name,start_time,end_time,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(company.id,required(value.name,'名称'),required(value.start_time,'開始'),required(value.end_time,'終了'),Number(value.sort_order??0),now(),now()).lastInsertRowid);json(res,201,{id});return true;}
  const breakDelete=url.pathname.match(/^\/api\/v1\/admin\/fixed-breaks\/(\d+)$/);if(req.method==='DELETE'&&breakDelete){db.prepare('UPDATE company_fixed_breaks SET active=0,updated_at=? WHERE id=? AND company_id=?').run(now(),Number(breakDelete[1]),company.id);json(res,200,{ok:true});return true;}
  if(req.method==='POST'&&url.pathname==='/api/v1/admin/menu-items'){const {value}=await bodyJson(req);const id=Number(db.prepare('INSERT INTO line_menu_items(company_id,code,label,parent_id,department_id,process_id,product_id,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(company.id,required(value.code,'コード'),required(value.label,'表示名'),value.parent_id??null,value.department_id??null,value.process_id??null,value.product_id??null,Number(value.sort_order??0),now(),now()).lastInsertRowid);json(res,201,{id});return true;}
  const menuPatch=url.pathname.match(/^\/api\/v1\/admin\/menu-items\/(\d+)$/);if(req.method==='PATCH'&&menuPatch){const {value}=await bodyJson(req),id=Number(menuPatch[1]),cur=one('SELECT * FROM line_menu_items WHERE id=? AND company_id=?',id,company.id);if(!cur)return fail(res,new Error('メニューがありません'),404),true;db.prepare('UPDATE line_menu_items SET label=?,parent_id=?,department_id=?,process_id=?,product_id=?,active=?,sort_order=?,updated_at=? WHERE id=?').run(value.label??cur.label,value.parent_id===undefined?cur.parent_id:value.parent_id,value.department_id===undefined?cur.department_id:value.department_id,value.process_id===undefined?cur.process_id:value.process_id,value.product_id===undefined?cur.product_id:value.product_id,value.active===undefined?cur.active:value.active?1:0,Number(value.sort_order??cur.sort_order),now(),id);json(res,200,{ok:true});return true;}
  if(req.method==='GET'&&url.pathname==='/api/v1/admin/work-session-candidates'){const q=url.searchParams;json(res,200,{sessions:rows("SELECT w.*,p.name process_name FROM work_sessions w JOIN processes p ON p.id=w.process_id WHERE w.company_id=? AND w.work_date=? AND w.employee_id=? AND w.process_id=? AND w.status='completed' ORDER BY w.started_at",company.id,required(q.get('date'),'作業日'),required(q.get('employee_id'),'担当者'),required(q.get('process_id'),'工程'))});return true;}
  if(req.method==='POST'&&url.pathname==='/api/v1/admin/work-session-links'){const {value}=await bodyJson(req);for(const id of value.work_session_ids??[])db.prepare('INSERT OR IGNORE INTO work_session_links(individual_process_result_id,work_session_id,linked_at) VALUES(?,?,?)').run(required(value.individual_process_result_id,'個人加工実績'),id,now());json(res,201,{ok:true});return true;}
  return false;
}
