CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY, username TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY, actor_user_id INTEGER REFERENCES users(id), action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, details_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS companies (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS company_settings (company_id INTEGER PRIMARY KEY REFERENCES companies(id), standard_end_time TEXT NOT NULL DEFAULT '17:30', grace_minutes INTEGER NOT NULL DEFAULT 30, break_mode TEXT NOT NULL DEFAULT 'line' CHECK(break_mode IN ('none','line','fixed','admin')), line_enabled INTEGER NOT NULL DEFAULT 1, unfinished_notification_enabled INTEGER NOT NULL DEFAULT 1, timezone TEXT NOT NULL DEFAULT 'Asia/Tokyo', updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS company_fixed_breaks (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), name TEXT NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS departments (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS employees (id INTEGER PRIMARY KEY, legacy_id TEXT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, department_id INTEGER REFERENCES departments(id), line_user_key TEXT UNIQUE, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS processes (id INTEGER PRIMARY KEY, legacy_id TEXT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), allocation_target INTEGER NOT NULL DEFAULT 1, dashboard_role TEXT, active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS flavors (id INTEGER PRIMARY KEY, legacy_id TEXT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_items (id INTEGER PRIMARY KEY, legacy_id TEXT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, item_type TEXT NOT NULL CHECK(item_type IN ('raw','processed_lotus','semi_finished_chips','finished','flavor','packaging')), department_id INTEGER REFERENCES departments(id), product_id INTEGER, flavor_id INTEGER REFERENCES flavors(id), storage_unit TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY, legacy_id TEXT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), content_amount_g INTEGER, flavor_id INTEGER REFERENCES flavors(id), sales_unit TEXT NOT NULL DEFAULT 'bag', standard_price INTEGER NOT NULL DEFAULT 0, inventory_item_id INTEGER REFERENCES inventory_items(id), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS partners (id INTEGER PRIMARY KEY, legacy_id TEXT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, partner_type TEXT NOT NULL DEFAULT 'both', payment_terms_days INTEGER, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS product_packaging_components (id INTEGER PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id), packaging_item_id INTEGER NOT NULL REFERENCES inventory_items(id), quantity_per_product INTEGER NOT NULL CHECK(quantity_per_product>=0), effective_from TEXT NOT NULL, effective_to TEXT, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS flavor_recipes (id INTEGER PRIMARY KEY, flavor_id INTEGER NOT NULL REFERENCES flavors(id), name TEXT NOT NULL, effective_from TEXT NOT NULL, effective_to TEXT, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS flavor_recipe_components (id INTEGER PRIMARY KEY, recipe_id INTEGER NOT NULL REFERENCES flavor_recipes(id), inventory_item_id INTEGER NOT NULL REFERENCES inventory_items(id), standard_quantity_g INTEGER NOT NULL CHECK(standard_quantity_g>=0), allocation_rule TEXT);

CREATE TABLE IF NOT EXISTS receipt_batches (id INTEGER PRIMARY KEY, receipt_date TEXT NOT NULL, partner_id INTEGER REFERENCES partners(id), department_id INTEGER NOT NULL REFERENCES departments(id), status TEXT NOT NULL DEFAULT 'confirmed', memo TEXT, created_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS receipt_lines (id INTEGER PRIMARY KEY, batch_id INTEGER NOT NULL REFERENCES receipt_batches(id), item_id INTEGER NOT NULL REFERENCES inventory_items(id), lot_no TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), unit TEXT NOT NULL, amount INTEGER NOT NULL DEFAULT 0 CHECK(amount>=0), unit_cost REAL NOT NULL DEFAULT 0, expiry_date TEXT);
CREATE TABLE IF NOT EXISTS inventory_lots (id INTEGER PRIMARY KEY, item_id INTEGER NOT NULL REFERENCES inventory_items(id), lot_no TEXT NOT NULL, received_or_made_on TEXT NOT NULL, unit_cost REAL NOT NULL DEFAULT 0, expires_on TEXT, UNIQUE(item_id,lot_no));
CREATE TABLE IF NOT EXISTS inventory_movements (id INTEGER PRIMARY KEY, lot_id INTEGER NOT NULL REFERENCES inventory_lots(id), business_date TEXT NOT NULL, movement_type TEXT NOT NULL, quantity_delta INTEGER NOT NULL, source_type TEXT NOT NULL, source_id INTEGER, department_id INTEGER REFERENCES departments(id), memo TEXT, created_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS process_runs (id INTEGER PRIMARY KEY, work_date TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), process_id INTEGER NOT NULL REFERENCES processes(id), product_id INTEGER REFERENCES products(id), input_item_id INTEGER REFERENCES inventory_items(id), output_item_id INTEGER REFERENCES inventory_items(id), input_lot_id INTEGER REFERENCES inventory_lots(id), input_qty_g INTEGER NOT NULL CHECK(input_qty_g>=0), output_qty_g INTEGER NOT NULL CHECK(output_qty_g>=0), waste_qty_g INTEGER NOT NULL DEFAULT 0 CHECK(waste_qty_g>=0), status TEXT NOT NULL DEFAULT 'confirmed', memo TEXT, created_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS individual_process_results (id INTEGER PRIMARY KEY, process_run_id INTEGER REFERENCES process_runs(id), work_date TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), process_id INTEGER NOT NULL REFERENCES processes(id), employee_id INTEGER NOT NULL REFERENCES employees(id), input_lot_id INTEGER REFERENCES inventory_lots(id), input_qty_g INTEGER NOT NULL CHECK(input_qty_g>=0), waste_qty_g INTEGER NOT NULL DEFAULT 0 CHECK(waste_qty_g>=0), output_qty_g INTEGER NOT NULL CHECK(output_qty_g>=0), work_session_id INTEGER, memo TEXT, status TEXT NOT NULL DEFAULT 'confirmed', created_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS production_batches (id INTEGER PRIMARY KEY, production_date TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), lot_no TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'confirmed', memo TEXT, created_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS production_consumptions (id INTEGER PRIMARY KEY, batch_id INTEGER NOT NULL REFERENCES production_batches(id), item_id INTEGER NOT NULL REFERENCES inventory_items(id), inventory_lot_id INTEGER REFERENCES inventory_lots(id), quantity INTEGER NOT NULL CHECK(quantity>=0), unit TEXT NOT NULL, consumption_type TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS production_outputs (id INTEGER PRIMARY KEY, batch_id INTEGER NOT NULL REFERENCES production_batches(id), product_id INTEGER REFERENCES products(id), item_id INTEGER NOT NULL REFERENCES inventory_items(id), inventory_lot_id INTEGER REFERENCES inventory_lots(id), completed_weight_g INTEGER NOT NULL DEFAULT 0 CHECK(completed_weight_g>=0), completed_count INTEGER NOT NULL DEFAULT 0 CHECK(completed_count>=0), count_unit TEXT NOT NULL DEFAULT 'bag', defect_qty INTEGER NOT NULL DEFAULT 0, waste_qty INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS work_sessions (id INTEGER PRIMARY KEY, company_id INTEGER REFERENCES companies(id), employee_id INTEGER NOT NULL REFERENCES employees(id), department_id INTEGER NOT NULL REFERENCES departments(id), process_id INTEGER NOT NULL REFERENCES processes(id), product_id INTEGER REFERENCES products(id), work_date TEXT NOT NULL, started_at TEXT NOT NULL, ended_at TEXT, break_minutes INTEGER NOT NULL DEFAULT 0, minutes INTEGER, source_type TEXT NOT NULL CHECK(source_type IN ('line','web','manual_exception')), status TEXT NOT NULL DEFAULT 'running', external_id TEXT UNIQUE, break_mode TEXT, exception_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work_breaks (id INTEGER PRIMARY KEY, work_session_id INTEGER NOT NULL REFERENCES work_sessions(id), started_at TEXT NOT NULL, ended_at TEXT, minutes INTEGER, source_type TEXT NOT NULL DEFAULT 'line', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS line_users (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), employee_id INTEGER NOT NULL REFERENCES employees(id), line_user_id TEXT NOT NULL, display_name TEXT, is_manager INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, linked_at TEXT NOT NULL, unlinked_at TEXT, UNIQUE(company_id,line_user_id), UNIQUE(company_id,employee_id));
CREATE TABLE IF NOT EXISTS line_registration_codes (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), employee_id INTEGER NOT NULL REFERENCES employees(id), code_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS line_menu_items (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), code TEXT NOT NULL, label TEXT NOT NULL, parent_id INTEGER REFERENCES line_menu_items(id), department_id INTEGER REFERENCES departments(id), process_id INTEGER REFERENCES processes(id), product_id INTEGER REFERENCES products(id), active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(company_id,code));
CREATE TABLE IF NOT EXISTS external_events (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), source TEXT NOT NULL, event_id TEXT NOT NULL, occurred_at TEXT, received_at TEXT NOT NULL, payload_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'received', response_json TEXT, error_message TEXT, processed_at TEXT, UNIQUE(company_id,source,event_id));
CREATE TABLE IF NOT EXISTS line_events (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), event_id TEXT, received_at TEXT NOT NULL, raw_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'received', processed_at TEXT, error_message TEXT);
CREATE TABLE IF NOT EXISTS work_session_corrections (id INTEGER PRIMARY KEY, work_session_id INTEGER NOT NULL REFERENCES work_sessions(id), reason TEXT NOT NULL, before_json TEXT NOT NULL, after_json TEXT NOT NULL, corrected_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work_session_links (id INTEGER PRIMARY KEY, individual_process_result_id INTEGER NOT NULL REFERENCES individual_process_results(id), work_session_id INTEGER NOT NULL REFERENCES work_sessions(id), linked_at TEXT NOT NULL, UNIQUE(individual_process_result_id,work_session_id));
CREATE TABLE IF NOT EXISTS notification_logs (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL REFERENCES companies(id), work_session_id INTEGER REFERENCES work_sessions(id), notification_type TEXT NOT NULL, recipient_type TEXT NOT NULL, recipient_key TEXT, status TEXT NOT NULL DEFAULT 'pending', payload_json TEXT NOT NULL DEFAULT '{}', external_event_id TEXT, created_at TEXT NOT NULL, sent_at TEXT);
CREATE TABLE IF NOT EXISTS labor_cost_rates (id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL REFERENCES employees(id), rate_type TEXT NOT NULL CHECK(rate_type IN ('hourly','monthly_management')), salary_amount INTEGER, weekday_count INTEGER, hours_per_day INTEGER NOT NULL DEFAULT 8, rate_amount REAL NOT NULL, effective_from TEXT NOT NULL, effective_to TEXT, source_note TEXT);
CREATE TABLE IF NOT EXISTS work_session_costs (id INTEGER PRIMARY KEY, work_session_id INTEGER NOT NULL UNIQUE REFERENCES work_sessions(id), labor_cost_rate_id INTEGER NOT NULL REFERENCES labor_cost_rates(id), process_id INTEGER NOT NULL REFERENCES processes(id), minutes INTEGER NOT NULL, labor_cost_amount INTEGER NOT NULL, calculated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS production_cost_pools (id INTEGER PRIMARY KEY, production_batch_id INTEGER REFERENCES production_batches(id), pool_type TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open');
CREATE TABLE IF NOT EXISTS process_labor_cost_allocations (id INTEGER PRIMARY KEY, cost_pool_id INTEGER NOT NULL REFERENCES production_cost_pools(id), process_id INTEGER NOT NULL REFERENCES processes(id), work_session_cost_id INTEGER NOT NULL REFERENCES work_session_costs(id), allocated_amount INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS shipment_batches (id INTEGER PRIMARY KEY, delivery_date TEXT NOT NULL, physical_shipment_date TEXT, department_id INTEGER NOT NULL REFERENCES departments(id), partner_id INTEGER NOT NULL REFERENCES partners(id), settlement_type TEXT NOT NULL CHECK(settlement_type IN ('cash','receivable')), due_date TEXT, status TEXT NOT NULL DEFAULT 'confirmed', memo TEXT, created_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shipment_lines (id INTEGER PRIMARY KEY, batch_id INTEGER NOT NULL REFERENCES shipment_batches(id), product_id INTEGER NOT NULL REFERENCES products(id), inventory_lot_id INTEGER REFERENCES inventory_lots(id), quantity INTEGER NOT NULL CHECK(quantity>0), unit TEXT NOT NULL DEFAULT 'bag', unit_price INTEGER NOT NULL CHECK(unit_price>=0), sales_amount INTEGER NOT NULL, direct_cost_amount INTEGER NOT NULL DEFAULT 0, gross_profit_amount INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS receivables (id INTEGER PRIMARY KEY, shipment_batch_id INTEGER NOT NULL UNIQUE REFERENCES shipment_batches(id), partner_id INTEGER NOT NULL REFERENCES partners(id), recognized_on TEXT NOT NULL, original_amount INTEGER NOT NULL, outstanding_amount INTEGER NOT NULL, due_date TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open');
CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY, partner_id INTEGER NOT NULL REFERENCES partners(id), received_on TEXT NOT NULL, amount INTEGER NOT NULL CHECK(amount>0), payment_method TEXT NOT NULL, memo TEXT, created_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payment_allocations (id INTEGER PRIMARY KEY, payment_id INTEGER NOT NULL REFERENCES payments(id), receivable_id INTEGER NOT NULL REFERENCES receivables(id), allocated_amount INTEGER NOT NULL CHECK(allocated_amount>0));
CREATE TABLE IF NOT EXISTS outsourcing_costs (id INTEGER PRIMARY KEY, occurred_on TEXT NOT NULL, amount INTEGER NOT NULL CHECK(amount>=0), scope_type TEXT NOT NULL CHECK(scope_type IN ('company','department','flavor')), department_id INTEGER REFERENCES departments(id), flavor_id INTEGER REFERENCES flavors(id), memo TEXT);

CREATE TABLE IF NOT EXISTS stocktakes (id INTEGER PRIMARY KEY, stocktake_date TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), status TEXT NOT NULL DEFAULT 'confirmed', created_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS stocktake_lines (id INTEGER PRIMARY KEY, stocktake_id INTEGER NOT NULL REFERENCES stocktakes(id), item_id INTEGER NOT NULL REFERENCES inventory_items(id), lot_id INTEGER REFERENCES inventory_lots(id), book_qty INTEGER NOT NULL, actual_qty INTEGER NOT NULL, difference_qty INTEGER NOT NULL, reason TEXT);
CREATE TABLE IF NOT EXISTS daily_closures (id INTEGER PRIMARY KEY, business_date TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id), status TEXT NOT NULL DEFAULT 'confirmed', confirmed_by INTEGER REFERENCES users(id), confirmed_at TEXT NOT NULL, UNIQUE(business_date,department_id));

CREATE INDEX IF NOT EXISTS idx_process_date ON process_runs(work_date,department_id,process_id);
CREATE INDEX IF NOT EXISTS idx_individual_date ON individual_process_results(work_date,employee_id,process_id);
CREATE INDEX IF NOT EXISTS idx_inventory_date ON inventory_movements(business_date,department_id);
CREATE INDEX IF NOT EXISTS idx_shipments_date ON shipment_batches(delivery_date,department_id);
CREATE INDEX IF NOT EXISTS idx_work_date ON work_sessions(work_date,department_id,process_id);
CREATE INDEX IF NOT EXISTS idx_line_users_employee ON line_users(company_id,employee_id,active);
CREATE INDEX IF NOT EXISTS idx_external_events_status ON external_events(company_id,status,received_at);
CREATE INDEX IF NOT EXISTS idx_line_events_event ON line_events(company_id,event_id,received_at);
CREATE INDEX IF NOT EXISTS idx_work_breaks_session ON work_breaks(work_session_id,started_at);
