import http from 'node:http';
import { existsSync, readFileSync } from 'node:fs';
import { extname, normalize, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { db, audit, now, transaction } from './db.js';
import { grossProfit, laborRate, periodRange, workMinutes, yieldRate } from './domain.js';
import { handlePhase2A } from './phase2a.js';

const root=resolve(import.meta.dirname,'..'); const port=Number(process.env.PORT??3100);
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml'};
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify({data}));};
const fail=(res,error,status=400)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify({error:{message:error.message??String(error)}}));};
const parseBody=async(req)=>{const chunks=[];for await(const chunk of req)chunks.push(chunk);const text=Buffer.concat(chunks).toString('utf8');return text?JSON.parse(text):{};};
const rows=(sql,...args)=>db.prepare(sql).all(...args), one=(sql,...args)=>db.prepare(sql).get(...args);
const required=(value,label)=>{if(value===undefined||value===null||value==='')throw new Error(`${label}は必須です`);return value;};
const nonnegative=(value,label)=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error(`${label}が不正です`);return n;};
function currentUser(){return one("SELECT id,username,display_name FROM users WHERE username='internal' AND active=1");}
function requireUser(){return currentUser();}
function getOrCreateLot(itemId,lotNo,date,unitCost=0){const found=one('SELECT * FROM inventory_lots WHERE item_id=? AND lot_no=?',itemId,lotNo);if(found)return found.id;return Number(db.prepare('INSERT INTO inventory_lots(item_id,lot_no,received_or_made_on,unit_cost) VALUES(?,?,?,?)').run(itemId,lotNo,date,unitCost).lastInsertRowid);}
function inventoryMove({lotId,date,type,qty,sourceType,sourceId,departmentId,memo=''}){db.prepare('INSERT INTO inventory_movements(lot_id,business_date,movement_type,quantity_delta,source_type,source_id,department_id,memo,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(lotId,date,type,qty,sourceType,sourceId,departmentId,memo,now());}
function dashboard(department,period,anchor){
  const dept=one('SELECT * FROM departments WHERE code=? AND active=1',department);if(!dept)throw new Error('部門が不正です'); const range=periodRange(period,anchor);
  const flow=rows(`SELECT p.id process_id,p.name,p.sort_order,COALESCE(SUM(r.input_qty_g),0) input_qty_g,COALESCE(SUM(r.output_qty_g),0) output_qty_g,COALESCE(SUM(r.waste_qty_g),0) waste_qty_g FROM processes p LEFT JOIN process_runs r ON r.process_id=p.id AND r.work_date BETWEEN ? AND ? AND r.status='confirmed' WHERE p.department_id=? AND p.active=1 AND p.dashboard_role='primary_process' GROUP BY p.id ORDER BY p.sort_order`,range.from,range.to,dept.id).map(r=>({...r,yield_rate:yieldRate(r.output_qty_g,r.input_qty_g)}));
  const completed=one(`SELECT COALESCE(SUM(o.completed_weight_g),0) weight_g,COALESCE(SUM(o.completed_count),0) count FROM production_outputs o JOIN production_batches b ON b.id=o.batch_id WHERE b.department_id=? AND b.production_date BETWEEN ? AND ? AND b.status='confirmed'`,dept.id,range.from,range.to);
  const sales=one(`SELECT COALESCE(SUM(l.sales_amount),0) amount,COALESCE(SUM(l.quantity),0) quantity FROM shipment_lines l JOIN shipment_batches b ON b.id=l.batch_id WHERE b.department_id=? AND b.delivery_date BETWEEN ? AND ? AND b.status='confirmed'`,dept.id,range.from,range.to);
  if(department==='produce'){
    const products=rows(`SELECT product.id product_id,product.name,
      COALESCE((SELECT SUM(r.output_qty_g) FROM process_runs r JOIN processes p ON p.id=r.process_id WHERE r.product_id=product.id AND r.work_date BETWEEN ? AND ? AND r.status='confirmed' AND p.dashboard_role='produce_harvest'),0) harvest_qty_g,
      COALESCE((SELECT SUM(r.output_qty_g) FROM process_runs r JOIN processes p ON p.id=r.process_id WHERE r.product_id=product.id AND r.work_date BETWEEN ? AND ? AND r.status='confirmed' AND p.dashboard_role='produce_selection'),0) selected_qty_g,
      COALESCE((SELECT SUM(r.waste_qty_g) FROM process_runs r JOIN processes p ON p.id=r.process_id WHERE r.product_id=product.id AND r.work_date BETWEEN ? AND ? AND r.status='confirmed' AND p.dashboard_role='produce_selection'),0) waste_qty_g,
      COALESCE((SELECT SUM(l.quantity) FROM shipment_lines l JOIN shipment_batches b ON b.id=l.batch_id WHERE l.product_id=product.id AND b.delivery_date BETWEEN ? AND ? AND b.status='confirmed'),0) shipped_qty_g,
      COALESCE((SELECT SUM(l.sales_amount) FROM shipment_lines l JOIN shipment_batches b ON b.id=l.batch_id WHERE l.product_id=product.id AND b.delivery_date BETWEEN ? AND ? AND b.status='confirmed'),0) sales_amount
      FROM products product WHERE product.department_id=? AND product.active=1 ORDER BY product.name`,range.from,range.to,range.from,range.to,range.from,range.to,range.from,range.to,range.from,range.to,dept.id).map(x=>({...x,yield_rate:yieldRate(x.selected_qty_g,x.harvest_qty_g)}));
    return {department:dept,period,range,produce:{products},closure:one('SELECT * FROM daily_closures WHERE business_date=? AND department_id=?',anchor,dept.id)??null};
  }
  const itemInventory=rows(`SELECT i.id,i.name,i.item_type,p.name product_name,f.name flavor_name,COALESCE(SUM(m.quantity_delta),0) quantity FROM inventory_items i LEFT JOIN inventory_lots l ON l.item_id=i.id LEFT JOIN inventory_movements m ON m.lot_id=l.id AND m.business_date<=? LEFT JOIN products p ON p.inventory_item_id=i.id LEFT JOIN flavors f ON f.id=i.flavor_id WHERE i.department_id=? AND i.active=1 AND i.item_type IN ('finished','flavor') GROUP BY i.id HAVING quantity<>0 ORDER BY i.item_type,p.name,f.name,i.name`,range.to,dept.id);
  return {department:dept,period,range,process_flow:flow,completed,finished_inventory:itemInventory.filter(x=>x.item_type==='finished'),flavor_inventory:itemInventory.filter(x=>x.item_type==='flavor'),shipment_sales_total:sales.amount,closure:one('SELECT * FROM daily_closures WHERE business_date=? AND department_id=?',anchor,dept.id)??null};
}

async function api(req,res,url){
  if(!['GET','HEAD'].includes(req.method)){const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)return fail(res,new Error('不正な送信元です'),403);}
  const user=requireUser(req,res);if(!user)return;
  if(await handlePhase2A(req,res,url,user))return;
  if(req.method==='GET'&&url.pathname==='/api/v1/dashboard'){try{return json(res,200,dashboard(url.searchParams.get('department')??'lotus',url.searchParams.get('period')??'day',url.searchParams.get('anchor')??new Date(Date.now()-86400000).toISOString().slice(0,10)));}catch(error){return fail(res,error);}}
  if(req.method==='GET'&&url.pathname==='/api/v1/dashboard/process-analysis'){const from=required(url.searchParams.get('from'),'開始日'),to=required(url.searchParams.get('to'),'終了日'),dept=one('SELECT id FROM departments WHERE code=?',url.searchParams.get('department')??'lotus');return json(res,200,{processes:rows(`SELECT p.name,COALESCE((SELECT SUM(r.input_qty_g) FROM process_runs r WHERE r.process_id=p.id AND r.work_date BETWEEN ? AND ? AND r.status='confirmed'),0) input_qty_g,COALESCE((SELECT SUM(r.output_qty_g) FROM process_runs r WHERE r.process_id=p.id AND r.work_date BETWEEN ? AND ? AND r.status='confirmed'),0) output_qty_g,COALESCE((SELECT SUM(r.waste_qty_g) FROM process_runs r WHERE r.process_id=p.id AND r.work_date BETWEEN ? AND ? AND r.status='confirmed'),0) waste_qty_g,COALESCE((SELECT SUM(w.minutes) FROM work_sessions w WHERE w.process_id=p.id AND w.work_date BETWEEN ? AND ? AND w.status='completed'),0) minutes,COALESCE((SELECT SUM(c.labor_cost_amount) FROM work_session_costs c JOIN work_sessions w ON w.id=c.work_session_id WHERE w.process_id=p.id AND w.work_date BETWEEN ? AND ?),0) labor_cost FROM processes p WHERE p.department_id=? ORDER BY p.sort_order`,from,to,from,to,from,to,from,to,from,to,dept.id).map(x=>({...x,yield_rate:yieldRate(x.output_qty_g,x.input_qty_g),productivity_g_h:Number(x.minutes)>0?Number(x.output_qty_g)/(Number(x.minutes)/60):null}))});}
  if(req.method==='GET'&&url.pathname==='/api/v1/dashboard/workforce-analysis'){const from=required(url.searchParams.get('from'),'開始日'),to=required(url.searchParams.get('to'),'終了日'),dept=one('SELECT id FROM departments WHERE code=?',url.searchParams.get('department')??'lotus');return json(res,200,{people:rows(`SELECT e.name employee,p.name process,SUM(i.input_qty_g) input_qty_g,SUM(i.output_qty_g) output_qty_g,SUM(i.waste_qty_g) waste_qty_g,SUM(COALESCE(w.minutes,0)) minutes FROM individual_process_results i JOIN employees e ON e.id=i.employee_id JOIN processes p ON p.id=i.process_id LEFT JOIN work_sessions w ON w.id=i.work_session_id WHERE i.department_id=? AND i.work_date BETWEEN ? AND ? AND i.status='confirmed' GROUP BY e.id,p.id ORDER BY e.name,p.sort_order`,dept.id,from,to).map(x=>({...x,yield_rate:yieldRate(x.output_qty_g,x.input_qty_g),productivity_g_h:Number(x.minutes)>0?Number(x.output_qty_g)/(Number(x.minutes)/60):null}))});}
  if(req.method==='GET'&&url.pathname==='/api/v1/dashboard/product-profitability'){const from=required(url.searchParams.get('from'),'開始日'),to=required(url.searchParams.get('to'),'終了日'),dept=one('SELECT id FROM departments WHERE code=?',url.searchParams.get('department')??'lotus');const products=rows(`SELECT p.name,SUM(l.sales_amount) sales_amount,SUM(l.direct_cost_amount) direct_cost_amount,SUM(l.gross_profit_amount) gross_profit_amount FROM shipment_lines l JOIN shipment_batches b ON b.id=l.batch_id JOIN products p ON p.id=l.product_id WHERE b.department_id=? AND b.delivery_date BETWEEN ? AND ? GROUP BY p.id ORDER BY p.name`,dept.id,from,to).map(x=>({...x,gross_margin_rate:Number(x.sales_amount)>0?Number(x.gross_profit_amount)/Number(x.sales_amount):null}));const shared=one(`SELECT COALESCE(SUM(a.allocated_amount),0) amount FROM process_labor_cost_allocations a JOIN production_cost_pools cp ON cp.id=a.cost_pool_id WHERE cp.department_id=? AND cp.pool_type='chips_total'`,dept.id).amount;return json(res,200,{products,sales_total:products.reduce((s,x)=>s+Number(x.sales_amount),0),chips_shared_labor_cost:shared});}
  if(req.method==='GET'&&url.pathname==='/api/v1/masters')return json(res,200,{departments:rows('SELECT * FROM departments WHERE active=1 ORDER BY sort_order'),processes:rows('SELECT * FROM processes ORDER BY department_id,sort_order'),employees:rows('SELECT * FROM employees WHERE active=1 ORDER BY name'),products:rows('SELECT * FROM products ORDER BY name'),flavors:rows('SELECT * FROM flavors ORDER BY name'),items:rows('SELECT * FROM inventory_items ORDER BY item_type,name'),partners:rows('SELECT * FROM partners ORDER BY name'),lots:rows(`SELECT l.id,l.item_id,l.lot_no,l.received_or_made_on,i.name item_name,i.department_id,i.storage_unit,COALESCE(SUM(m.quantity_delta),0) available_quantity FROM inventory_lots l JOIN inventory_items i ON i.id=l.item_id LEFT JOIN inventory_movements m ON m.lot_id=l.id WHERE i.active=1 GROUP BY l.id HAVING available_quantity>0 ORDER BY l.received_or_made_on DESC,i.name`)});
  const admin=requireUser(req,res,true);if(!admin)return;
  if(req.method==='POST'&&url.pathname==='/api/v1/masters/processes'){const i=await parseBody(req);const result=db.prepare('INSERT INTO processes(code,name,department_id,allocation_target,dashboard_role,active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?,?)').run(required(i.code,'コード'),required(i.name,'工程名'),required(i.department_id,'部門'),i.allocation_target===false?0:1,i.dashboard_role??null,Number(i.sort_order??999),now(),now());audit(user,'CREATE','process',result.lastInsertRowid,i);return json(res,201,{id:Number(result.lastInsertRowid)});}
  if(req.method==='POST'&&url.pathname==='/api/v1/masters/employees'){const i=await parseBody(req),stamp=now();const result=db.prepare('INSERT INTO employees(legacy_id,code,name,department_id,line_user_key,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)').run(i.legacy_id??null,required(i.code,'コード'),required(i.name,'氏名'),i.department_id??null,i.line_user_key??null,stamp,stamp);audit(user,'CREATE','employee',result.lastInsertRowid,i);return json(res,201,{id:Number(result.lastInsertRowid)});}
  if(req.method==='POST'&&url.pathname==='/api/v1/masters/flavors'){const i=await parseBody(req),stamp=now();const result=db.prepare('INSERT INTO flavors(legacy_id,code,name,active,created_at,updated_at) VALUES(?,?,?,1,?,?)').run(i.legacy_id??null,required(i.code,'コード'),required(i.name,'名称'),stamp,stamp);audit(user,'CREATE','flavor',result.lastInsertRowid,i);return json(res,201,{id:Number(result.lastInsertRowid)});}
  if(req.method==='POST'&&url.pathname==='/api/v1/masters/items'){const i=await parseBody(req),stamp=now();const result=db.prepare('INSERT INTO inventory_items(legacy_id,code,name,item_type,department_id,flavor_id,storage_unit,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)').run(i.legacy_id??null,required(i.code,'コード'),required(i.name,'名称'),required(i.item_type,'在庫区分'),i.department_id??null,i.flavor_id??null,i.storage_unit??(i.item_type==='packaging'?'piece':i.item_type==='finished'||i.item_type==='flavor'?'bag':'g'),stamp,stamp);audit(user,'CREATE','inventory_item',result.lastInsertRowid,i);return json(res,201,{id:Number(result.lastInsertRowid)});}
  if(req.method==='POST'&&url.pathname==='/api/v1/masters/products'){const i=await parseBody(req),stamp=now();const result=db.prepare('INSERT INTO products(legacy_id,code,name,department_id,content_amount_g,flavor_id,sales_unit,standard_price,inventory_item_id,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1,?,?)').run(i.legacy_id??null,required(i.code,'コード'),required(i.name,'商品名'),required(i.department_id,'部門'),i.content_amount_g??null,i.flavor_id??null,i.sales_unit??'bag',Number(i.standard_price??0),i.inventory_item_id??null,stamp,stamp);audit(user,'CREATE','product',result.lastInsertRowid,i);return json(res,201,{id:Number(result.lastInsertRowid)});}
  if(req.method==='POST'&&url.pathname==='/api/v1/masters/partners'){const i=await parseBody(req),stamp=now();const result=db.prepare('INSERT INTO partners(legacy_id,code,name,partner_type,payment_terms_days,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)').run(i.legacy_id??null,required(i.code,'コード'),required(i.name,'名称'),i.partner_type??'both',i.payment_terms_days??null,stamp,stamp);audit(user,'CREATE','partner',result.lastInsertRowid,i);return json(res,201,{id:Number(result.lastInsertRowid)});}
  const processMatch=url.pathname.match(/^\/api\/v1\/masters\/processes\/(\d+)$/);if(req.method==='PATCH'&&processMatch){const i=await parseBody(req),id=Number(processMatch[1]),cur=one('SELECT * FROM processes WHERE id=?',id);if(!cur)return fail(res,new Error('工程がありません'),404);db.prepare('UPDATE processes SET name=?,sort_order=?,active=?,dashboard_role=?,updated_at=? WHERE id=?').run(i.name??cur.name,Number(i.sort_order??cur.sort_order),i.active===undefined?cur.active:i.active?1:0,i.dashboard_role===undefined?cur.dashboard_role:i.dashboard_role,now(),id);audit(user,'UPDATE','process',id,i);return json(res,200,{ok:true});}
  if(req.method==='POST'&&url.pathname==='/api/v1/receipts'){try{const i=await parseBody(req);const id=transaction(()=>{const batch=Number(db.prepare('INSERT INTO receipt_batches(receipt_date,partner_id,department_id,memo,created_by,created_at) VALUES(?,?,?,?,?,?)').run(required(i.receipt_date,'入荷日'),i.partner_id??null,required(i.department_id,'部門'),i.memo??'',user.id,now()).lastInsertRowid);for(const line of i.lines??[]){const qty=nonnegative(required(line.quantity,'数量'),'数量');if(qty===0)throw new Error('数量は0より大きくしてください');const amount=nonnegative(line.amount??0,'金額'),unitCost=amount/qty;const result=db.prepare('INSERT INTO receipt_lines(batch_id,item_id,lot_no,quantity,unit,amount,unit_cost,expiry_date) VALUES(?,?,?,?,?,?,?,?)').run(batch,required(line.item_id,'品目'),required(line.lot_no,'ロット'),qty,line.unit??'g',amount,unitCost,line.expiry_date??null);const lot=getOrCreateLot(line.item_id,line.lot_no,i.receipt_date,unitCost);inventoryMove({lotId:lot,date:i.receipt_date,type:'receipt',qty,sourceType:'receipt_line',sourceId:Number(result.lastInsertRowid),departmentId:i.department_id});}audit(user,'CREATE','receipt',batch);return batch;});return json(res,201,{id});}catch(error){return fail(res,error);}}
  if(req.method==='POST'&&url.pathname==='/api/v1/process-runs'){try{const i=await parseBody(req),department=one('SELECT code FROM departments WHERE id=?',required(i.department_id,'部門'));if(!department)throw new Error('部門が不正です');const productId=department.code==='produce'?required(i.product_id,'商品'):i.product_id??null;if(productId&&!one('SELECT id FROM products WHERE id=? AND department_id=? AND active=1',productId,i.department_id))throw new Error('部門に対応する商品ではありません');const created=transaction(()=>{const result=db.prepare('INSERT INTO process_runs(work_date,department_id,process_id,product_id,input_item_id,output_item_id,input_lot_id,input_qty_g,output_qty_g,waste_qty_g,memo,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(required(i.work_date,'作業日'),i.department_id,required(i.process_id,'工程'),productId,i.input_item_id??null,i.output_item_id??null,required(i.input_lot_id,'使用材料'),nonnegative(i.input_qty_g,'使用量'),nonnegative(i.output_qty_g,'出来高'),nonnegative(i.waste_qty_g??0,'破棄'),i.memo??'',user.id,now(),now());const runId=Number(result.lastInsertRowid),individualResult=db.prepare('INSERT INTO individual_process_results(process_run_id,work_date,department_id,process_id,employee_id,input_lot_id,input_qty_g,waste_qty_g,output_qty_g,memo,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(runId,i.work_date,i.department_id,i.process_id,required(i.employee_id,'担当者'),i.input_lot_id,i.input_qty_g,i.waste_qty_g??0,i.output_qty_g,i.memo??'',user.id,now(),now());audit(user,'CREATE','process_run',runId);return {id:runId,individual_result_id:Number(individualResult.lastInsertRowid)};});return json(res,201,created);}catch(error){return fail(res,error);}}
  if(req.method==='POST'&&url.pathname==='/api/v1/work-time-exceptions'){try{const i=await parseBody(req),minutes=workMinutes(required(i.started_at,'開始日時'),required(i.ended_at,'終了日時'),nonnegative(i.break_minutes??0,'休憩時間'));if(minutes<=0)throw new Error('作業時間は0分より長くしてください');const result=db.prepare("INSERT INTO work_sessions(employee_id,department_id,process_id,work_date,started_at,ended_at,break_minutes,minutes,source_type,status,exception_reason,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'completed',?,?,?)").run(required(i.employee_id,'担当者'),required(i.department_id,'部門'),required(i.process_id,'工程'),required(i.work_date,'作業日'),i.started_at,i.ended_at,Number(i.break_minutes??0),minutes,'manual_exception',required(i.exception_reason,'例外入力理由'),now(),now());audit(user,'CREATE','work_time_exception',result.lastInsertRowid,{reason:i.exception_reason});return json(res,201,{id:Number(result.lastInsertRowid),minutes});}catch(error){return fail(res,error);}}
  if(req.method==='POST'&&url.pathname==='/api/v1/individual-process-results'){try{const i=await parseBody(req);const result=db.prepare('INSERT INTO individual_process_results(process_run_id,work_date,department_id,process_id,employee_id,input_lot_id,input_qty_g,waste_qty_g,output_qty_g,work_session_id,memo,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(i.process_run_id??null,required(i.work_date,'作業日'),required(i.department_id,'部門'),required(i.process_id,'工程'),required(i.employee_id,'担当者'),i.input_lot_id??null,nonnegative(i.input_qty_g,'使用量'),nonnegative(i.waste_qty_g??0,'破棄量'),nonnegative(i.output_qty_g,'出来高'),i.work_session_id??null,i.memo??'',user.id,now(),now());audit(user,'CREATE','individual_process_result',result.lastInsertRowid);return json(res,201,{id:Number(result.lastInsertRowid)});}catch(error){return fail(res,error);}}
  if(req.method==='POST'&&url.pathname==='/api/v1/work-sessions/start'){try{const i=await parseBody(req);const running=one("SELECT id FROM work_sessions WHERE employee_id=? AND status='running'",i.employee_id);if(running)throw new Error('進行中の作業があります');const started=i.started_at??now(),date=i.work_date??started.slice(0,10);const result=db.prepare("INSERT INTO work_sessions(employee_id,department_id,process_id,work_date,started_at,source_type,status,external_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'running',?,?,?)").run(required(i.employee_id,'担当者'),required(i.department_id,'部門'),required(i.process_id,'工程'),date,started,i.source_type??'line',i.external_id??null,now(),now());return json(res,201,{id:Number(result.lastInsertRowid)});}catch(error){return fail(res,error);}}
  const stop=url.pathname.match(/^\/api\/v1\/work-sessions\/(\d+)\/stop$/);if(req.method==='POST'&&stop){try{const i=await parseBody(req),id=Number(stop[1]),session=one('SELECT * FROM work_sessions WHERE id=?',id);if(!session||session.status!=='running')throw new Error('進行中の作業がありません');const ended=i.ended_at??now(),minutes=workMinutes(session.started_at,ended,i.break_minutes??0);transaction(()=>{db.prepare("UPDATE work_sessions SET ended_at=?,break_minutes=?,minutes=?,status='completed',updated_at=? WHERE id=?").run(ended,Number(i.break_minutes??0),minutes,now(),id);const rate=one('SELECT * FROM labor_cost_rates WHERE employee_id=? AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1',session.employee_id,session.work_date,session.work_date);if(rate){const hourly=laborRate({rateType:rate.rate_type,rateAmount:rate.rate_amount,salaryAmount:rate.salary_amount,weekdayCount:rate.weekday_count,hoursPerDay:rate.hours_per_day});db.prepare('INSERT INTO work_session_costs(work_session_id,labor_cost_rate_id,process_id,minutes,labor_cost_amount,calculated_at) VALUES(?,?,?,?,?,?)').run(id,rate.id,session.process_id,minutes,Math.round(hourly*minutes/60),now());}});return json(res,200,{minutes});}catch(error){return fail(res,error);}}
  if(req.method==='POST'&&url.pathname==='/api/v1/production-batches'){try{const i=await parseBody(req);const id=transaction(()=>{const batch=Number(db.prepare('INSERT INTO production_batches(production_date,department_id,lot_no,memo,created_by,created_at) VALUES(?,?,?,?,?,?)').run(required(i.production_date,'製造日'),required(i.department_id,'部門'),required(i.lot_no,'ロット'),i.memo??'',user.id,now()).lastInsertRowid);for(const o of i.outputs??[]){const lot=getOrCreateLot(o.item_id,`${i.lot_no}-${o.product_id??o.item_id}`,i.production_date,0);const weight=nonnegative(o.completed_weight_g??0,'完成重量'),count=nonnegative(o.completed_count??0,'完成数量');const result=db.prepare('INSERT INTO production_outputs(batch_id,product_id,item_id,inventory_lot_id,completed_weight_g,completed_count,count_unit,defect_qty,waste_qty) VALUES(?,?,?,?,?,?,?,?,?)').run(batch,o.product_id??null,o.item_id,lot,weight,count,o.count_unit??'bag',nonnegative(o.defect_qty??0,'不良'),nonnegative(o.waste_qty??0,'廃棄'));inventoryMove({lotId:lot,date:i.production_date,type:'production_output',qty:count>0?count:weight,sourceType:'production_output',sourceId:Number(result.lastInsertRowid),departmentId:i.department_id});}audit(user,'CREATE','production_batch',batch);return batch;});return json(res,201,{id});}catch(error){return fail(res,error);}}
  if(req.method==='POST'&&url.pathname==='/api/v1/shipments'){try{const i=await parseBody(req);const id=transaction(()=>{const batch=Number(db.prepare('INSERT INTO shipment_batches(delivery_date,physical_shipment_date,department_id,partner_id,settlement_type,due_date,memo,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(required(i.delivery_date,'納品日'),i.physical_shipment_date??null,required(i.department_id,'部門'),required(i.partner_id,'納品先'),required(i.settlement_type,'決済区分'),i.due_date??null,i.memo??'',user.id,now()).lastInsertRowid);let total=0;for(const l of i.lines??[]){const sales=Number(l.quantity)*Number(l.unit_price),profit=grossProfit(sales,l.direct_cost_amount??0);const result=db.prepare('INSERT INTO shipment_lines(batch_id,product_id,inventory_lot_id,quantity,unit,unit_price,sales_amount,direct_cost_amount,gross_profit_amount) VALUES(?,?,?,?,?,?,?,?,?)').run(batch,l.product_id,l.inventory_lot_id??null,l.quantity,l.unit??'bag',l.unit_price,sales,l.direct_cost_amount??0,profit.amount);total+=sales;if(l.inventory_lot_id)inventoryMove({lotId:l.inventory_lot_id,date:i.delivery_date,type:'delivery',qty:-Number(l.quantity),sourceType:'shipment_line',sourceId:Number(result.lastInsertRowid),departmentId:i.department_id});}if(i.settlement_type==='receivable'){if(!i.due_date)throw new Error('売掛の入金予定日は必須です');db.prepare('INSERT INTO receivables(shipment_batch_id,partner_id,recognized_on,original_amount,outstanding_amount,due_date) VALUES(?,?,?,?,?,?)').run(batch,i.partner_id,i.delivery_date,total,total,i.due_date);}audit(user,'CREATE','shipment',batch);return batch;});return json(res,201,{id});}catch(error){return fail(res,error);}}
  if(req.method==='GET'&&url.pathname==='/api/v1/receivables')return json(res,200,{receivables:rows(`SELECT r.*,p.name partner_name FROM receivables r JOIN partners p ON p.id=r.partner_id WHERE (? IS NULL OR r.status=?) ORDER BY r.due_date`,url.searchParams.get('status'),url.searchParams.get('status'))});
  if(req.method==='POST'&&url.pathname==='/api/v1/payments'){try{const i=await parseBody(req);const id=transaction(()=>{const payment=Number(db.prepare('INSERT INTO payments(partner_id,received_on,amount,payment_method,memo,created_by,created_at) VALUES(?,?,?,?,?,?,?)').run(i.partner_id,i.received_on,i.amount,i.payment_method??'bank',i.memo??'',user.id,now()).lastInsertRowid);let sum=0;for(const a of i.allocations??[]){const rec=one('SELECT * FROM receivables WHERE id=?',a.receivable_id);if(!rec||Number(a.amount)>Number(rec.outstanding_amount))throw new Error('消込額が売掛残高を超えています');db.prepare('INSERT INTO payment_allocations(payment_id,receivable_id,allocated_amount) VALUES(?,?,?)').run(payment,a.receivable_id,a.amount);const remain=Number(rec.outstanding_amount)-Number(a.amount);db.prepare('UPDATE receivables SET outstanding_amount=?,status=? WHERE id=?').run(remain,remain===0?'paid':'open',a.receivable_id);sum+=Number(a.amount);}if(sum>Number(i.amount))throw new Error('消込額が入金額を超えています');audit(user,'CREATE','payment',payment);return payment;});return json(res,201,{id});}catch(error){return fail(res,error);}}
  if(req.method==='POST'&&url.pathname==='/api/v1/daily-closures'){const i=await parseBody(req);db.prepare('INSERT INTO daily_closures(business_date,department_id,status,confirmed_by,confirmed_at) VALUES(?,?,?,?,?) ON CONFLICT(business_date,department_id) DO UPDATE SET status=excluded.status,confirmed_by=excluded.confirmed_by,confirmed_at=excluded.confirmed_at').run(i.business_date,i.department_id,'confirmed',user.id,now());audit(user,'CLOSE','daily_closure',`${i.business_date}:${i.department_id}`);return json(res,200,{ok:true});}
  return fail(res,new Error('対象が見つかりません'),404);
}
function staticFile(res,url){let path=url.pathname==='/'?'/index.html':url.pathname;path=normalize(path).replace(/^(\.\.[/\\])+/, '');const file=resolve(root,'public',`.${path}`);if(!file.startsWith(resolve(root,'public'))||!existsSync(file)){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream','x-content-type-options':'nosniff'});res.end(readFileSync(file));}
export const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host??'localhost'}`);try{res.setHeader('x-frame-options','DENY');res.setHeader('referrer-policy','same-origin');if(url.pathname==='/healthz'){db.prepare('SELECT 1').get();return json(res,200,{ok:true});}if(url.pathname.startsWith('/api/'))await api(req,res,url);else staticFile(res,url);}catch(error){console.error(error);if(!res.headersSent)fail(res,error,500);else res.end();}});
if(resolve(process.argv[1]??'')===fileURLToPath(import.meta.url))server.listen(port,'0.0.0.0',()=>console.log(`Manufacturing Management listening on ${port}`));
